# All SpaceVim option below [option] section
[options]

    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    disabled_plugins=["srcery-vim"]

    enable_guicolors = true
    statusline_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false

    # MY OWN OPTIONS
    autocomplete_method = "coc"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
#vimcompatible = true 

# ----------------- SpaceVim 添加的各种 layers ---------------------------------

[[layers]]
    name = "colorscheme"


[[layers]]
  name="shell"
  default_position = "bottom"
  default_height = "30"
  enable = true

# 禁用 SpaceVim 的 checkers layer
[[layers]]
  name = "checkers"
  enable = false

# 版本控制
#[[layers]]
#  name = "VersionControl"
#  enable-gtm-status = true
# [[layers]]
  # name = "lsp"
  # filetypes = [
    # "c",
    # "cpp"
  # ]
  # [layers.override_cmd]
    # c = ["clangd"]

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
  name="lang#c"

[[layers]]
  name = "format"



# ----------------- 添加的插件 -------------------------------------------------
#

[[custom_plugins]]
  name = "mhartington/oceanic-next"
  merged = 0
# 任务系统插件
[[custom_plugins]]
    name = 'skywind3000/asyncrun.vim'
[[custom_plugins]]
    name = 'skywind3000/asynctasks.vim'

# 基于语义的c/c++/objc的语法高亮 如果使用clangd ，则需要coc.nvim
[[custom_plugins]]
  name = 'jackguo380/vim-lsp-cxx-highlight'

[[custom_plugins]]
   name = 'neoclide/coc.nvim'
   merge = 0
   build =  'yarn install --frozen-lockfile'

# 主要用于快速搜索 文件, buffer 和 函数
[[custom_plugins]]
    name = "Yggdroot/LeaderF"
    build = "./install.sh"

# glsl 语法高亮
[[custom_plugins]]
    name = "tikhomirov/vim-glsl"

# 括号补全
[[custom_plugins]]
    name = "tpope/vim-surround"

# vim-floaterm
[[custom_plugins]]
    name = "voldikss/vim-floaterm"

[[custom_plugins]]
    name = "voldikss/LeaderF-floaterm"


[[custom_plugins]]
    name = 'puremourning/vimspector'

[[custom_plugins]]
    name = "tpope/vim-surround"
