require("catppuccin").setup({
	flavour = "mocha", -- latte, frappe, macchiato, mocha
	background = {
		-- :h background
		light = "latte",
		dark = "mocha",
	},
	dim_inactive = {
		enabled = false,
		shade = "dark",
		percentage = 0.15,
	},
	transparent_background = true,
	term_colors = false,
	compile = {
		enabled = true,
		path = vim.fn.stdpath "cache" .. "/catppuccin",
	},
	styles = {
		comments = { "italic" },
		conditionals = { "italic" },
		loops = {},
		functions = {},
		keywords = {},
		strings = {},
		variables = {},
		numbers = {},
		booleans = {},
		properties = {},
		types = {},
		operators = {},
	},
	integrations = {
		treesitter = true,
		native_lsp = {
			enabled = true,
			virtual_text = {
				errors = { "italic" },
				hints = { "italic" },
				warnings = { "italic" },
				information = { "italic" },
			},
			underlines = {
				errors = { "underline" },
				hints = { "underline" },
				warnings = { "underline" },
				information = { "underline" },
			},
		},
		coc_nvim = false,
		lsp_trouble = false,
		cmp = true,
		lsp_saga = false,
		gitgutter = false,
		gitsigns = true,
		leap = false,
		telescope = {
			enabled = true,
			transparent_panel = true,
			transparent_background = true,
		},
		nvimtree = {
			enabled = true,
			show_root = true,
			transparent_panel = true,
			transparent_background = true,
		},
		neotree = {
			enabled = false,
			show_root = true,
			transparent_panel = false,
		},
		dap = {
			enabled = true,
			enable_ui = true,
		},
		which_key = true,
		indent_blankline = {
			enabled = true,
			colored_indent_levels = false,
		},
		dashboard = true,
		neogit = false,
		vim_sneak = false,
		fern = false,
		barbar = true,
		bufferline = true,
		markdown = true,
		lightspeed = false,
		ts_rainbow = false,
		hop = false,
		notify = true,
		telekasten = true,
		symbols_outline = true,
		mini = false,
		aerial = false,
		vimwiki = true,
		beacon = true,
	},
	color_overrides = {
		mocha = {
			mauve = "#B48EAD",
			lavender = "#5E81AC",
			red = "#BF616A",
			--maroon = "#f98080",
			--peach = "#D08770",
			yellow = "#8FA1C1",
			green = "#A3BE8C",
			teal = "#8FBCBB",
			-- sky = "#88C0D0",
			sapphire = "#95b9d0",
			blue = "#88C0D0",
			text = "#ECEFF4",
			subtext1 = "#ACBCD3",
			subtext0 = "#6F7988",
			--overlay2 = "#B0B9C2",
			overlay1 = "#9FB0C1",
			overlay0 = "#8090B1",
			surface2 = "#6C7C9B",
			surface1 = "#556178",
			surface0 = "#4C566A",
			mantle = "#434C5E",
			crust = "#3B4252",
			base = "#2E3440",
		}
	},
	custom_highlights = {},
})

vim.cmd [[colorscheme catppuccin]]
