-- local map = require("utils").map
--
-- map({ "n", "<F9>", ":lua require('dap').toggle_breakpoint()<CR>" })
-- map({ "n", "<F10>", ":lua require('dap').continue()<CR>" })
--
-- map({ "n", "<F5>", ":lua require('dap').step_over()<CR>" })
-- map({ "n", "<F6>", ":lua require('dap').step_into()<CR>" })
-- -- map({ "n", "<F3>", ":lua require('dap').step_out()<CR>" })
--
-- map({ "n", "<Leader>dk", ":lua require('dap.ui.variables').hover()<CR>" })
-- map({ "v", "<Leader>dkv", ":lua require('dap.ui.variables').visual_hover()<CR>" })
--
-- map({ "n", "<Leader>duh", ":lua require('dap.ui.widgets').hover()<CR>" })
-- map({ "n", "<Leader>duf", ":lua local widgets=require('dap.ui.widgets');widgets.centered_float(widgets.scopes)<CR>" })
--
-- map({ "n", "<Leader>dro", ":lua require('dap').repl.open()<CR>" })
-- map({ "n", "<Leader>drl", ":lua require('dap').repl.run_last()<CR>" })
--
-- map({ "n", "<Leader>dbc", ":lua require('dap').set_breakpoint(vim.fn.input('Breakpoint condition: '))<CR>" })
-- map({ "n", "<Leader>dbm", ":lua require('dap').set_breakpoint({ nil, nil, vim.fn.input('Log point message: ') })<CR>" })
-- map({ "n", "<Leader>dbt", ":lua require('dap').toggle_breakpoint()<CR>" })
--
-- map({ "n", "<Leader>dc", ":lua require('dap.ui.variables').scopes()<CR>" })
-- map({ "n", "<Leader>di", ":lua require('dapui').toggle()<CR>" })
