local mainMod = "SUPER"
local terminal = "alacritty"
local fileManager = "alacritty -e yazi"
local browser = "google-chrome-stable"
local hyprshell = "/usr/bin/hyprshell"
local backlightStep = (os.getenv("HOME") or "~") .. "/.config/hypr/scripts/backlight-step"
local volumeStep = (os.getenv("HOME") or "~") .. "/.config/hypr/scripts/volume-step"
local ensureHyprshell = [[systemctl --user is-active --quiet hyprshell.service || { rm -f "$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/hyprshell.sock"; systemctl --user start hyprshell.service; }]]
local restartWaybar = [[pkill -x waybar 2>/dev/null || true; nohup waybar >/tmp/waybar.log 2>&1 &]]
local startWaybar = [[pgrep -x waybar >/dev/null || exec waybar >/tmp/waybar.log 2>&1]]
local toggleWaybar = [[pkill -SIGUSR1 -x waybar]]
local configHome = os.getenv("XDG_CONFIG_HOME") or ((os.getenv("HOME") or "~") .. "/.config")
local hyprConfigDir = configHome .. "/hypr"
local hyprPackagePath = hyprConfigDir .. "/?.lua"

if package.path:find(hyprPackagePath, 1, true) == nil then
    package.path = hyprPackagePath .. ";" .. package.path
end

local function is_nwg_displays_config(path)
    local file = io.open(path, "r")
    if file == nil then
        return false
    end

    local header = file:read(2048) or ""
    file:close()

    return header:find("Generated by nwg-displays", 1, true) ~= nil
end

local function load_config_module(name)
    package.loaded[name] = nil
    return require(name)
end

hl.on("hyprland.start", function()
    hl.exec_cmd("sh -c 'systemctl --user stop dunst.service 2>/dev/null || true; pgrep -x swaync >/dev/null || swaync'")
    hl.exec_cmd("sh -c '" .. startWaybar .. "'")
    hl.exec_cmd("sh -c '" .. ensureHyprshell .. "'")
end)

-- nwg-displays writes monitors.lua alongside monitors.conf for Lua configs.
if is_nwg_displays_config(hyprConfigDir .. "/monitors.lua") then
    load_config_module("monitors")
else
    load_config_module("monitor-defaults")
end

hl.env("XMODIFIERS", "@im=fcitx")
hl.env("QT_IM_MODULES", "wayland;fcitx;ibus")
hl.env("QT_IM_MODULE", "fcitx")
hl.env("GTK_IM_MODULE", "fcitx")
hl.env("SDL_IM_MODULE", "fcitx")
hl.env("GLFW_IM_MODULE", "ibus")

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,
        active_opacity = 0.98,
        inactive_opacity = 0.94,
        fullscreen_opacity = 1.0,

        shadow = {
            enabled = true,
            range = 12,
            render_power = 3,
            color = "rgba(111827aa)",
        },

        blur = {
            enabled = true,
            size = 8,
            passes = 2,
            new_optimizations = true,
            ignore_opacity = true,
            xray = true,
            noise = 0.05,
            contrast = 0.95,
            brightness = 0.85,
            vibrancy = 0.18,
            popups = true,
            popups_ignorealpha = 0.35,
            input_methods = true,
            input_methods_ignorealpha = 0.35,
        },
    },
})

load_config_module("workspace-layout")

for _, namespace in ipairs({
    "waybar",
    "hyprshell_launcher",
    "hyprshell_overview",
    "hyprshell_switch",
    "swaync-control-center",
    "swaync-notification-window",
}) do
    hl.layer_rule({
        match = { namespace = namespace },
        blur = true,
        blur_popups = true,
        ignore_alpha = 0.25,
    })
end

load_config_module("keymap").setup({
    main_mod = mainMod,
    terminal = terminal,
    file_manager = fileManager,
    browser = browser,
    hyprshell = hyprshell,
    backlight_step = backlightStep,
    volume_step = volumeStep,
    ensure_hyprshell = ensureHyprshell,
    restart_waybar = restartWaybar,
    toggle_waybar = toggleWaybar,
})
